services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hackathon
    ports:
      - "15432:5432"
    volumes:
      - ./development/db:/docker-entrypoint-initdb.d